services:
    amenophis.social:
        class: Amenophis\Bundle\SocialBundle\Service\SocialManager
        arguments: [@doctrine.orm.entity_manager, @security.context, @event_dispatcher, %amenophis.social.entity.class%]

    amenophis.social.twig:
        class: Amenophis\Bundle\SocialBundle\Twig\SocialExtension
        arguments: [@amenophis.social]
        tags:
            - { name: twig.extension }